identity:
  association:
    # cron schedule to move expired associations
    expire: '0 0 0 * * ?'
  session:
    # cron schedule to delete expired sessions
    expire: '0 0 0 * * ?'
  # 10 years
  association-t-t-l: 311040000
  # how many create key at one time
  amount-keys-to-create: 20
  # identity hostname
  hostname: 'identity.local'
  # use root keystore or selfsign new certificates.
  use-server-key: false
  # email notification
  email:
    # sender
    hostname: 'server@identity.local'
    # subject
    subject: 'Session has been created'
    # message body
    body: 'Token: {0}\nClient secret: {1}\nSession id: {2}\nUrl: {3}'
  # key generator
  self-key-generator:
    # issuer for all new certificates
    issuer-name: 'identity'
    # seed for creating new keys
    secure-random-seed: 'seed'
    # length of the serial number
    serial-number-length: 20
    # time-to-live of the new certificates
    certificate-valid-t-s: 8100000
  # long-term keys
  long-term-keys:
    # key store
    key-store: 'long.pkcs12'
    # key store password
    key-store-password: 'store-long'
    # key password
    key-password: 'long'
    # key store type
    key-store-type: 'pkcs12'
  # short-term keys
  short-term-keys:
    # key store
    key-store: 'short.pkcs12'
    # key store password
    key-store-password: 'store-short'
    # key password
    key-password: 'short'
    # key store type
    key-store-type: 'pkcs12'
  # used short-term keys
  used-short-term-keys:
    # key store
    key-store: 'usedshort.pkcs12'
    # key store password
    key-store-password: 'used-short'
    # key password
    key-password: 'ushort'
    # key store type
    key-store-type: 'pkcs12'
  # url for invite sending
  on-bind-url: '_matrix/federation/v1/3pid/onbind'
  # port for invite sending
  on-bind-port: 8448
  # protocol for invite sending
  on-bind-protocol: 'https'
  # enable strict validation of the certifications
  trustall: false

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost/identity'
    username: 'jeon'
    password: 'jeon'
  mail:
    username: 'test'
    password: 'test'
    host: 'localhost'
    protocol: 'smtp'
    port: '593'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
      mail.smtp.ssl.enable: true
  security:
    basic:
      enabled: false
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

